-- Rename AppTemplate enum values for new supply chain apps
ALTER TYPE "AppTemplate" RENAME VALUE 'REORDER_DASHBOARD' TO 'INVENTORY_COMMAND_CENTER';
ALTER TYPE "AppTemplate" RENAME VALUE 'STOCK_ALERTS' TO 'DEMAND_FULFILLMENT';
ALTER TYPE "AppTemplate" RENAME VALUE 'SUPPLIER_PERFORMANCE' TO 'PROCUREMENT_HUB';
