import { BrainEntry, BrainEntryVersion, ChangeRequest, BrainStats } from './brain-types'

export const MOCK_BRAIN_ENTRIES: BrainEntry[] = [
  {
    id: 'brain-001',
    type: 'CONSTRAINT',
    domain: 'PROCUREMENT',
    status: 'ACTIVE',
    aiContextWeight: 'HIGH',
    title: 'Supplier Concentration Limit',
    summary: 'No single supplier may exceed 40% of category spend without CEO approval.',
    body: `## Policy\n\nTo protect against supply chain concentration risk, no single supplier may account for more than **40% of total spend** within any procurement category.\n\n## Rationale\n\nThis policy was established following a 2021 incident where our primary plastics supplier had a factory fire, causing a 6-week production halt. We had 78% concentration with that supplier at the time.`,
    conditions: ['Single supplier share exceeds 40% of category spend', 'New supplier contract would push concentration above threshold'],
    actions: ['Escalate to VP Procurement', 'Require CEO sign-off before proceeding', 'Explore alternative suppliers before committing'],
    exceptions: ['Emergency procurement situations with Plant Manager approval', 'Categories with fewer than 3 qualified suppliers (documented exception required)'],
    tags: ['supplier-risk', 'procurement', 'concentration', 'approval'],
    version: 3,
    effectiveDate: '2022-01-01',
    expiryDate: null,
    ownerId: 'user-001',
    owner: { id: 'user-001', name: 'Sarah Chen', image: null },
    createdById: 'user-001',
    createdAt: '2022-01-01T10:00:00Z',
    updatedAt: '2024-04-15T14:30:00Z',
  },
  {
    id: 'brain-002',
    type: 'RULE',
    domain: 'INVENTORY',
    status: 'ACTIVE',
    aiContextWeight: 'HIGH',
    title: 'Safety Stock Reorder Policy',
    summary: 'Trigger reorder when on-hand inventory drops below 2 weeks of average demand.',
    body: `## Rule\n\nFor all A-class and B-class SKUs, initiate a purchase order when on-hand inventory falls below **14 days of average demand** (calculated on a rolling 90-day basis).\n\n## Calculation\n\nReorder Point = (Average Daily Demand × 14) + Safety Stock Buffer\n\nSafety Stock Buffer = 20% of reorder point for A-class SKUs, 10% for B-class.`,
    conditions: ['On-hand inventory < 14 days of rolling 90-day average demand', 'Applies to A-class and B-class SKUs only'],
    actions: ['Auto-generate draft PO for procurement review', 'Notify inventory planner via system alert', 'Default order quantity = EOQ or MOQ, whichever is higher'],
    exceptions: ['C-class SKUs: reorder at 7 days', 'Seasonal SKUs: use seasonal demand model instead', 'Items on supplier allocation: escalate to procurement manager'],
    tags: ['reorder', 'inventory', 'safety-stock', 'sku-classification'],
    version: 2,
    effectiveDate: '2023-06-01',
    expiryDate: null,
    ownerId: 'user-002',
    owner: { id: 'user-002', name: 'Marcus Rodriguez', image: null },
    createdById: 'user-002',
    createdAt: '2023-06-01T09:00:00Z',
    updatedAt: '2024-02-10T11:00:00Z',
  },
  {
    id: 'brain-003',
    type: 'KNOWLEDGE',
    domain: 'PROCUREMENT',
    status: 'ACTIVE',
    aiContextWeight: 'MEDIUM',
    title: 'Supplier X Always Ships Late',
    summary: 'Supplier X (FastMetals Ltd) consistently delivers 3-5 days after the PO due date — plan accordingly.',
    body: `## Context\n\nDespite what their sales team says, FastMetals Ltd has delivered on or before the PO due date only **3 times in the last 2 years** (out of 47 orders).\n\n## What this means in practice\n\nWhen placing orders with FastMetals, add 5 business days to their quoted lead time for planning purposes. Do not book production slots that depend on their delivery arriving on time.\n\n## History\n\nThis has been flagged in QBRs twice. Their account manager acknowledges the issue and blames their third-party carrier. It has not been resolved as of April 2026.`,
    conditions: [],
    actions: [],
    exceptions: [],
    tags: ['fastmetals', 'supplier-performance', 'lead-time', 'planning-buffer'],
    version: 1,
    effectiveDate: null,
    expiryDate: null,
    ownerId: 'user-001',
    owner: { id: 'user-001', name: 'Sarah Chen', image: null },
    createdById: 'user-001',
    createdAt: '2024-03-15T16:00:00Z',
    updatedAt: '2024-03-15T16:00:00Z',
  },
  {
    id: 'brain-004',
    type: 'PROCESS',
    domain: 'PRODUCTION',
    status: 'ACTIVE',
    aiContextWeight: 'MEDIUM',
    title: 'Customer Escalation Handling',
    summary: 'Step-by-step process for handling a customer escalation when an order is at risk of being late.',
    body: `## Process\n\nWhen a customer order is flagged as at-risk (will not ship by promised date), follow this process within **4 business hours** of identification.\n\n### Steps\n\n1. **Notify the customer proactively** — do not wait for them to call. Send a templated email with the new expected ship date.\n2. **Offer a solution** — expedited shipping at our cost, or partial shipment of available units.\n3. **Escalate to Plant Manager** if the delay is >5 business days.\n4. **Log the root cause** in the production system (material shortage, equipment failure, labor, supplier delay, forecast error).\n5. **Follow up in 48 hours** to confirm customer received the shipment or updated ETA.`,
    conditions: ['Sales order is flagged at-risk', 'Promised ship date cannot be met'],
    actions: ['Notify customer within 4 hours', 'Offer expedited shipping or partial shipment', 'Escalate to Plant Manager if delay >5 days', 'Log root cause in system'],
    exceptions: ['Orders < $500: email notification only, no call required'],
    tags: ['escalation', 'customer-service', 'production', 'on-time-delivery'],
    version: 4,
    effectiveDate: '2021-01-01',
    expiryDate: null,
    ownerId: 'user-003',
    owner: { id: 'user-003', name: 'Jamie Park', image: null },
    createdById: 'user-003',
    createdAt: '2021-01-01T08:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'brain-005',
    type: 'AGREEMENT',
    domain: 'PROCUREMENT',
    status: 'ACTIVE',
    aiContextWeight: 'HIGH',
    title: 'Precision Parts Inc — Master Supply Agreement',
    summary: 'Key commercial terms for Precision Parts Inc: 8-week lead time, $10K MOQ, net-45 payment, 2% quality penalty clause.',
    body: `## Agreement Summary\n\n**Supplier:** Precision Parts Inc\n**Contract Period:** Jan 1, 2024 – Dec 31, 2025\n**Category:** CNC machined components\n\n## Key Terms\n\n| Term | Value |\n|------|-------|\n| Lead Time | 8 weeks from PO confirmation |\n| MOQ | $10,000 per order line |\n| Payment | Net-45 from delivery |\n| Price Escalation | CPI-linked, reviewed annually in December |\n| Quality Penalty | 2% of PO value if defect rate >0.5% |\n| Exclusivity | Non-exclusive |\n| Termination Notice | 90 days written notice |`,
    conditions: [],
    actions: [],
    exceptions: [],
    tags: ['precision-parts', 'contract', 'cnc', 'terms'],
    version: 1,
    effectiveDate: '2024-01-01',
    expiryDate: '2025-12-31',
    ownerId: 'user-001',
    owner: { id: 'user-001', name: 'Sarah Chen', image: null },
    createdById: 'user-001',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'brain-006',
    type: 'CONSTRAINT',
    domain: 'FINANCE',
    status: 'DRAFT',
    aiContextWeight: 'HIGH',
    title: 'PO Approval Thresholds',
    summary: 'Purchase orders above $25K require Director approval; above $100K require VP approval.',
    body: `## Thresholds\n\n| Amount | Required Approver |\n|--------|------------------|\n| < $10,000 | Buyer (self-approve) |\n| $10,000 – $25,000 | Procurement Manager |\n| $25,001 – $100,000 | Director of Operations |\n| > $100,000 | VP of Operations + CFO |\n\nEmergency purchases (production-critical, <24h turnaround needed): Plant Manager can approve any amount up to $50K, must be ratified by VP within 48 hours.`,
    conditions: ['PO is being raised for any spend category'],
    actions: ['Route PO to correct approver based on value', 'Block PO submission until required approval obtained'],
    exceptions: ['Emergency purchases: Plant Manager approves up to $50K with post-hoc VP ratification'],
    tags: ['approval', 'finance', 'purchasing', 'limits'],
    version: 1,
    effectiveDate: null,
    expiryDate: null,
    ownerId: 'user-002',
    owner: { id: 'user-002', name: 'Marcus Rodriguez', image: null },
    createdById: 'user-002',
    createdAt: '2024-04-10T09:00:00Z',
    updatedAt: '2024-04-10T09:00:00Z',
  },
]

export const MOCK_VERSION_HISTORY: BrainEntryVersion[] = [
  {
    id: 'ver-001-3',
    entryId: 'brain-001',
    version: 3,
    title: 'Supplier Concentration Limit',
    body: 'Updated threshold from 35% to 40% following board review.',
    changeNote: 'Updated threshold from 35% to 40% after Q1 supplier review and board approval.',
    changedById: 'user-001',
    changedBy: { id: 'user-001', name: 'Sarah Chen' },
    createdAt: '2024-04-15T14:30:00Z',
    aiContextWeight: 'HIGH',
    status: 'ACTIVE',
  },
  {
    id: 'ver-001-2',
    entryId: 'brain-001',
    version: 2,
    title: 'Supplier Concentration Limit',
    body: 'Added exception clause for categories with fewer than 3 qualified suppliers.',
    changeNote: 'Added exception for thin supplier markets after feedback from procurement team.',
    changedById: 'user-002',
    changedBy: { id: 'user-002', name: 'Marcus Rodriguez' },
    createdAt: '2023-08-20T10:00:00Z',
    aiContextWeight: 'HIGH',
    status: 'ACTIVE',
  },
  {
    id: 'ver-001-1',
    entryId: 'brain-001',
    version: 1,
    title: 'Supplier Concentration Limit',
    body: 'Initial capture.',
    changeNote: null,
    changedById: 'user-001',
    changedBy: { id: 'user-001', name: 'Sarah Chen' },
    createdAt: '2022-01-01T10:00:00Z',
    aiContextWeight: 'HIGH',
    status: 'ACTIVE',
  },
]

export const MOCK_CHANGE_REQUESTS: ChangeRequest[] = [
  {
    id: 'cr-001',
    entryId: 'brain-001',
    entryTitle: 'Supplier Concentration Limit',
    entryType: 'CONSTRAINT',
    title: 'Increase threshold to 50% for strategic suppliers',
    description: 'After completing the new supplier audit program, I believe strategic certified suppliers should be allowed up to 50% concentration. Our audit gives us enough visibility to manage the risk.',
    proposedBody: 'Updated body: threshold increases to 50% for suppliers who have completed the strategic audit certification...',
    status: 'PENDING',
    requestedById: 'user-003',
    requestedBy: { id: 'user-003', name: 'Jamie Park', image: null },
    createdAt: '2024-04-16T09:00:00Z',
    updatedAt: '2024-04-16T09:00:00Z',
  },
  {
    id: 'cr-002',
    entryId: 'brain-002',
    entryTitle: 'Safety Stock Reorder Policy',
    entryType: 'RULE',
    title: 'Adjust C-class SKU reorder point from 7 to 5 days',
    description: 'C-class SKUs are low-value and we have reliable local suppliers. 7 days is unnecessarily conservative and ties up working capital.',
    proposedBody: 'Updated: C-class SKUs reorder at 5 days of demand instead of 7...',
    status: 'PENDING',
    requestedById: 'user-002',
    requestedBy: { id: 'user-002', name: 'Marcus Rodriguez', image: null },
    createdAt: '2024-04-14T11:30:00Z',
    updatedAt: '2024-04-14T11:30:00Z',
  },
]

export const MOCK_BRAIN_STATS: BrainStats = {
  total: 6,
  activeCount: 5,
  draftCount: 1,
  byType: {
    RULE: 1,
    PROCESS: 1,
    CONSTRAINT: 2,
    KNOWLEDGE: 1,
    AGREEMENT: 1,
  },
  byDomain: {
    PROCUREMENT: 3,
    INVENTORY: 1,
    PRODUCTION: 1,
    PLANNING: 0,
    LOGISTICS: 0,
    QUALITY: 0,
    FINANCE: 1,
    HR: 0,
    OTHER: 0,
  },
  pendingChangeRequests: 2,
}
